import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabaseClient';
import {financeSnapshot} from '../utils/financeDashboard';
import {exportToCSV} from '../utils/csvExport';
async function readAll(table){let rows=[];for(let start=0;;start+=500){const {data,error}=await supabase.from(table).select('*').order('id').range(start,start+499);if(error)throw error;rows.push(...data);if(data.length<500)return rows;}}
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Managua',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money=(v,c)=>new Intl.NumberFormat('es-NI',{style:'currency',currency:c}).format(v);
export default function FinanceDashboard(){
 const [state,setState]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0),[accommodationId,setAccommodationId]=useState(''),[from,setFrom]=useState(()=>day().slice(0,7)+'-01'),[to,setTo]=useState(day);
 useEffect(()=>{let live=true;setLoading(true);setError('');Promise.all(['ota_commission_charges','ota_commission_payments','reservations','finance_transactions','accommodations'].map(readAll)).then(([charges,payments,reservations,transactions,accommodations])=>{if(live)setState({charges,payments,reservations,transactions,accommodations});}).catch(e=>{if(live){setState(null);setError(e.message);}}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[version]);
 const invalid=from&&to&&from>to;
 const summary=state&&!invalid?financeSnapshot({...state,accommodationId,from,to,today:day()}):null;
 const rows=state&&!invalid?state.accommodations.filter(a=>!accommodationId||a.id===accommodationId).flatMap(a=>{const s=financeSnapshot({...state,accommodationId:a.id,from,to,today:day()});return Object.entries(s.currencies).map(([currency,t])=>({name:a.name,currency,reservations:t.reservationCount,...t,id:a.id}));}):[];
 return <div className="ro-dashboard"><div className="ro-dashboard-hero"><div><h2>Finanzas de la OTA</h2><p>Comisiones, cobros y flujo de caja de Reserva Ometepe.</p></div><button className="ro-btn ro-btn-ghost" disabled={loading} onClick={()=>setVersion(v=>v+1)}>Actualizar</button></div>
 <div className="ro-panel-toolbar"><label>Desde <input className="ro-input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta <input className="ro-input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Alojamiento <select className="ro-input" value={accommodationId} onChange={e=>setAccommodationId(e.target.value)}><option value="">Todos</option>{state?.accommodations.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><Link className="ro-btn ro-btn-primary" to="/finanzas/collections">Registrar cobros y abonos</Link><Link className="ro-btn ro-btn-ghost" to="/finanzas/transactions">Registrar ingreso o gasto</Link></div>
 {(error||invalid)&&<p className="ro-alert" role="alert">{error||'La fecha inicial debe ser anterior a la final.'}</p>}{loading?<p>Cargando finanzas…</p>:summary&&<>
 {Object.entries(summary.currencies).map(([currency,t])=><section className="ro-panel" key={currency}><h3>{currency==='USD'?'Dólares estadounidenses':'Córdobas nicaragüenses'}</h3><div className="ro-dashboard-grid">{[['issued','Comisiones emitidas en el período'],['collected','Comisiones cobradas en el período'],['balance','Saldo pendiente actual'],['overdue','Saldo vencido actual'],['otherIncome','Otros ingresos confirmados'],['expenses','Gastos confirmados'],['result','Resultado de caja del período'],['reservationValue','Valor de reservas · pago al alojamiento']].map(([key,label])=><div className="ro-stat-card" key={key}><div className="ro-stat-card-body"><div className="ro-stat-card-value">{money(t[key],currency)}</div><div className="ro-stat-card-label">{label}</div></div></div>)}</div></section>)}
 <p>Comisiones emitidas: fecha de emisión. Cobrado: fecha de abono. Reservas: fecha de llegada. Saldos pendientes y vencidos: situación actual. Resultado de caja = comisiones cobradas + otros ingresos confirmados − gastos confirmados. El valor de las reservas pertenece al alojamiento.</p><p>Para evitar duplicados, los registros manuales «commission» y «potential_commission» no se suman como otros ingresos. Los cobros de comisión se contabilizan desde sus abonos.</p>
 <section className="ro-panel"><div className="ro-panel-toolbar"><h3>Resumen por alojamiento</h3><button className="ro-btn ro-btn-ghost" onClick={()=>exportToCSV('finanzas-por-alojamiento',rows,[{key:'name',label:'Alojamiento'},{key:'currency',label:'Moneda'},{key:'reservations',label:'Reservas'},{key:'issued',label:'Comisiones emitidas'},{key:'collected',label:'Cobrado'},{key:'balance',label:'Saldo actual'},{key:'overdue',label:'Vencido'}])}>Exportar CSV</button></div><div className="ro-table-wrap"><table className="ro-table"><thead><tr><th>Alojamiento</th><th>Moneda</th><th>Reservas</th><th>Emitido</th><th>Cobrado</th><th>Saldo actual</th><th>Vencido</th></tr></thead><tbody>{rows.map(r=><tr key={r.id+r.currency}><td><Link to={`/alojamiento/accommodations?hotel=${r.id}`}>{r.name}</Link></td><td>{r.currency}</td><td>{r.reservations}</td><td>{money(r.issued,r.currency)}</td><td>{money(r.collected,r.currency)}</td><td>{money(r.balance,r.currency)}</td><td>{money(r.overdue,r.currency)}</td></tr>)}</tbody></table></div></section></>}
 </div>;
}
