import React, {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import AccommodationForm from './AccommodationForm';
import accommodationTable from '../config/tables/accommodations';
import {HOST_FIELDS,hostPayload} from '../auth/access';
import {SUBMISSION_LABELS,listingIssues,editableSubmission} from '../utils/listingWorkflow';
const table={...accommodationTable,columns:accommodationTable.columns.filter(c=>HOST_FIELDS.has(c.key)),sections:accommodationTable.sections.filter(s=>s.key!=='config')};
export default function ListingSubmissions({admin=false,userId,onApproved}) {
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notes,setNotes]=useState('');
 const reload=useCallback(async()=>{setLoading(true);let q=supabase.from('owner_submissions').select('*').eq('submission_type','accommodation').order('created_at',{ascending:false});if(!admin)q=q.eq('owner_id',userId);const {data,error}=await q;setError(error?.message||'');setRows(data||[]);setLoading(false);},[admin,userId]);
 useEffect(()=>{reload();},[reload]);
 async function save(payload,intent){setError('');const clean=hostPayload(payload);if(intent==='submitted'){const issues=listingIssues(clean);if(issues.length){setError('Antes de enviar completa: '+issues.join(', '));return;}}setBusy(true);try{const {data,error}=await supabase.rpc('save_listing_submission',{submission_id:selected.id||null,listing_payload:clean,send_for_review:intent==='submitted'});if(error)throw error;setSelected(data);await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function review(decision){if(busy)return;if(decision!=='approved'&&!notes.trim()){setError('Explica qué debe corregir el anfitrión.');return;}setBusy(true);setError('');try{const {data,error}=await supabase.rpc('review_listing_submission',{submission_id:selected.id,decision,review_note:notes.trim()});if(error)throw error;setSelected(null);setNotes('');await reload();if(decision==='approved')onApproved?.(data);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="ro-panel"><div className="ro-panel-toolbar"><h3>{admin?'Revisión de alojamientos':'Mis borradores y solicitudes'}</h3>{!admin&&!selected&&<button className="ro-btn ro-btn-primary" onClick={()=>setSelected({payload:{currency:'USD'},status:'draft'})}>Crear alojamiento</button>}<button className="ro-btn ro-btn-ghost" disabled={busy} onClick={reload}>Actualizar</button></div>
 <p>{admin?'Revisa la información enviada por el anfitrión. Aprobar crea una ficha oculta; complétala con habitaciones y decide cuándo publicarla.':'Guarda tu avance, envíalo a revisión y consulta la respuesta de Reserva Ometepe. El huésped paga directamente al alojamiento.'}</p>
 {error&&<p className="ro-alert" role="alert">{error}</p>}{loading&&<p>Cargando…</p>}
 {selected?<><button className="ro-btn ro-btn-ghost" disabled={busy} onClick={()=>{setSelected(null);setNotes('');}}>Volver a solicitudes</button><p><strong>{SUBMISSION_LABELS[selected.status]}</strong>{selected.review_notes&&' · '+selected.review_notes}</p>
 {!admin&&editableSubmission(selected.status)?<AccommodationForm key={selected.id||'new-draft'} table={table} record={selected.payload} draft saving={busy} onSave={save} submitLabel="Guardar borrador" secondarySubmitLabel="Enviar a revisión"/>:<><dl>{table.columns.map(c=><React.Fragment key={c.key}><dt><strong>{c.label}</strong></dt><dd>{Array.isArray(selected.payload[c.key])?selected.payload[c.key].join(', '):String(selected.payload[c.key]??'—')}</dd></React.Fragment>)}</dl>{selected.payload.main_image_url&&<img src={selected.payload.main_image_url} alt="Foto del alojamiento" style={{maxWidth:320}}/>}</>}
 {admin&&selected.status==='submitted'&&<div><label>Respuesta para el anfitrión<textarea className="ro-input" value={notes} onChange={e=>setNotes(e.target.value)}/></label>{[['approved','Aprobar ficha'],['changes_requested','Solicitar cambios'],['rejected','Rechazar']].map(([d,l])=><button key={d} className="ro-btn ro-btn-primary" disabled={busy} onClick={()=>review(d)}>{l}</button>)}</div>}</>:<div className="ro-table-wrap"><table className="ro-table"><thead><tr><th>Alojamiento</th><th>Estado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.payload.name||'Sin nombre'}</td><td>{SUBMISSION_LABELS[r.status]}</td><td>{new Date(r.created_at).toLocaleDateString('es-NI')}</td><td><button className="ro-btn ro-btn-ghost" onClick={()=>{setSelected(r);setNotes('');}}>Abrir</button></td></tr>)}</tbody></table>{!loading&&!rows.length&&<p>No hay solicitudes de alojamiento todavía.</p>}</div>}
 </section>;
}
